# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudcurl < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudcurl/cli-releases/releases/download/v0.0.1/cloudcurl_darwin_amd64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "167cc35f86bc28ba733f8dff3663309ff412c908a1dd84f07a710f23632caafa"

      def install
        bin.install "cloudcurl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudcurl/cli-releases/releases/download/v0.0.1/cloudcurl_darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "82cdac8b4c21ee72287ae538722348bce3fcb96a350f31072c14c8462e81081b"

      def install
        bin.install "cloudcurl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/cloudcurl/cli-releases/releases/download/v0.0.1/cloudcurl_linux_amd64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "b67e8748632926b3769e8d9d69235576e5939a088235be16b3d88328b879153a"
      def install
        bin.install "cloudcurl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/cloudcurl/cli-releases/releases/download/v0.0.1/cloudcurl_linux_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "449b8a1e5b40f042317cd961a187edf13a5fae5c83f32435b6b0deba15d2e051"
      def install
        bin.install "cloudcurl"
      end
    end
  end
end
