# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudcurl < Formula
  desc ""
  homepage ""
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudcurl/homebrew-tap/releases/download/"",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "f89f7c7f4f42481f0b7f27b3131c98208bc7e17982ad286b011b8a20f3b750d5"

      def install
        bin.install "cloudcurl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudcurl/homebrew-tap/releases/download/"",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "0144ef408335b2106ae03276e0570d1fa6d2428b1f1ba500a07b18a7d2dae03e"

      def install
        bin.install "cloudcurl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/cloudcurl/homebrew-tap/releases/download/"",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "217a95b31dfc38b81ce1d6b3ab3445bd178008b4529678adb0162945a3ab9136"
      def install
        bin.install "cloudcurl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/cloudcurl/homebrew-tap/releases/download/"",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "c18a7a4443cc098aad34a32c25353df274a28774b741ec101b5740343716cfae"
      def install
        bin.install "cloudcurl"
      end
    end
  end
end
