# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudcurl < Formula
  desc ""
  homepage ""
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudcurl/cli/releases/download/v0.0.6/cloudcurl_darwin_amd64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "a7637135153131cc9104bda9cae06b66ccc996f0e6b61166f780039212459d40"

      def install
        bin.install "cloudcurl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cloudcurl/cli/releases/download/v0.0.6/cloudcurl_darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "2a6d0e39717afd782398eee80a0635e051bdd082c569fc0256ac6247deb17fe5"

      def install
        bin.install "cloudcurl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/cloudcurl/cli/releases/download/v0.0.6/cloudcurl_linux_amd64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "1a63e16413548f2752166bd10dd489af5380e4a7d24b6718779f4d3cc29806e5"
      def install
        bin.install "cloudcurl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/cloudcurl/cli/releases/download/v0.0.6/cloudcurl_linux_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream"
        ]
      sha256 "f787f4e6e81ce3a2d5fffbec9ac69c8450cd1c7bf97a55204c30a5d24b115a5e"
      def install
        bin.install "cloudcurl"
      end
    end
  end
end
